<<<<<<< HEAD
version: "3.9"

=======
>>>>>>> Authentification/connexion
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
<<<<<<< HEAD

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: geckoCooking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
=======
    command: npm run dev
  postgres:
      image: postgres:16
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: geckoCooking
      ports:
        - "5432:5432"
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
>>>>>>> Authentification/connexion

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

<<<<<<< HEAD
volumes:
  postgres_data:
  mongo_data:
=======
      # Déclaration des volumes
volumes:
  mongo_data:
>>>>>>> Authentification/connexion
